### ISSUE TITLE
Checksums do not match official distribution

### ISSUE THREAD

**Issue by aphirst** [iPotable/FossaMailBinaries#1]
As can be seen on [the Pale Moon website](https://www.palemoon.org/redist.shtml) (also applies to FossaMail),

> * The binaries and/or archives are completely UNALTERED. This includes addition or removal of any component of the browser or redistributing modified parts of the browser as-built (including, without limitation, predefined profile components, altered jar or omni files, or modified .exe or dll components)...

As evidenced by the PKGBUILD which links to these binaries, their checksums do not match those of the official releases.

In the PKGBUILD:
> * sha1sums_i686=('1e799ffbddd56d1acbbf905763ed0eebc32c161d')
> * sha1sums_x86_64=('c73187744613591ae16625a447ab3d51bb1c56c1')

At [the official site](http://www.fosshub.com/FossaMail.html)
> * Linux x86 SHA1: 84c514efc2dc7d73acd07dbab03f54160d76dc98 
> * Linux x86_64 SHA1: 8d996f1d47c5d5950c43e8e08df2c3f6ffc3605b

I've been in touch with the developers, and have mentioned this in a few other places (in particular, [the AUR package using these binaries](https://aur.archlinux.org/packages/fossamail-bin/).

It is important to note that the PKGBUILD works perfectly when applied to a local copy of the official tarball, and indeed also appears (at least on my machine) to resolve an issue with the Lightning extension, [their official forums](https://forum.palemoon.org/viewtopic.php?f=34&t=11206).

**Comment by wolfbeast** [comment]
A quick investigation shows that the offered tarballs in this repo are rebuilds from source, differently configured that the official ones just looking at the omni and lib sizes included.
Since we have official binaries for this platform, you cannot just rebuild/reconfigure the client and then publish this as official. This rebuild has already shown to cause issues not present in the official binaries and is not exempted per default.

Please state why you have made a rebuild this time (as opposed to hosting the official binaries) and why/how you've reconfigured this, and if any source code/branding/user config changes were made, which ones.

**Comment by wolfbeast** [comment]
https://forum.palemoon.org/viewtopic.php?f=34&t=11206&p=80657#p80657

It's fine if you hack away for your own private use but you're impacting all Arch users here under our name.

Please understand you can't just make a reconfiguration like this. If you want to redistribute your own personal builds with your unofficial config, then you MUST use your own branding and not official branding. I thought we were already clear on this. Use some common sense!

**Comment by aphirst** [comment]
I still haven't yet been able to get in touch with anyone else regarding this, other than to advise a few other people about the potential issue. In the mean time it's relevant to point out that this repository contains packages for two versions, the current, and the previous. For the previous, the checksums do indeed match.

**Comment by wolfbeast** [comment]
I'll give it another day, then I'll send a Takedown request.

Please respond before then.

**Comment by iPotable** [comment]
Hi, sorry for my answer's delay. I talked to aphirst on IRC few minutes ago to explain the situation. I built the 25.2 version because it wasn't built after few days of the release on the github. Maybe I was too hurry and I made it wrong. My apologies. I would know your opinion, if you're still agree to let me copy the official binaries or if I should ask users to download it manually on FossHub. I will delete this repo if you ask me to do so. I cannot directly insert the download link from FossHub since it requires a http referer and it's not supported on pkgbuilds (and maybe but no sure, not allowed on aur rules). Also, if you have suggestions on what mozconfig file I should use and improvements for the pkgbuild for the -git aur package (https://aur.archlinux.org/packages/fossamail-git/), they're welcome.

**Comment by iPotable** [comment]
Okay I tried to upload this pkgbuild on aur and it was rejected by the server because it can't find the sources. I do not have a solution yet. :/ 
[PKGBUILD.txt](https://github.com/iPotable/FossaMailBinaries/files/164310/PKGBUILD.txt)

**Comment by iPotable** [comment]
package updated until we find a solution.

**Comment by wolfbeast** [comment]
What... so you built your own version just because I tagged a commit in the source tree?...
Don't do that. Tags in the source tree are for version control and build points, they aren't necessarily indicating that that commit is final; getting impatient and building from source to release based on that is **not** what you should do, even if you need your own builds.

See also:
https://forum.palemoon.org/viewtopic.php?f=37&t=10996

Also, as clearly stated, don't build your own versions with config changes unless there is a very good reason to do so (for Arch, there isn't, since we have official binaries). Don't just "wing it", okay?
If you have issues with getting distribution binaries or similar, talk to us.

**Comment by iPotable** [comment]
I think that I have somehow fixed the problem. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fossamail-bin
